# Generated by Django 3.1.5 on 2021-07-09 11:21

import API.models
import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('test1', models.BooleanField(default=False)),
                ('test2', models.BooleanField(default=False)),
                ('test3', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='English_Cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_English', models.CharField(max_length=100, null=True)),
                ('description_English', models.TextField(null=True)),
                ('content_English', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('title_French', models.CharField(max_length=100, null=True)),
                ('description_French', models.TextField(null=True)),
                ('content_French', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('title_Arabic', models.CharField(max_length=100, null=True)),
                ('description_Arabic', models.TextField(null=True)),
                ('content_Arabic', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='English Cards')),
                ('cover_image', models.ImageField(null=True, upload_to='English Cards')),
            ],
            options={
                'verbose_name_plural': 'English',
            },
        ),
        migrations.CreateModel(
            name='English_Slideshow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_English', models.CharField(max_length=100, null=True)),
                ('content_English', models.TextField(null=True)),
                ('title_French', models.CharField(max_length=100, null=True)),
                ('content_French', models.TextField(null=True)),
                ('title_Arabic', models.CharField(max_length=100, null=True)),
                ('content_Arabic', models.TextField(null=True)),
                ('image', models.ImageField(upload_to='English Slideshow')),
            ],
            options={
                'verbose_name_plural': 'English Slideshow',
            },
        ),
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Home_Slideshow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_English', models.CharField(max_length=100, null=True)),
                ('content_English', models.TextField(null=True)),
                ('title_French', models.CharField(max_length=100, null=True)),
                ('content_French', models.TextField(null=True)),
                ('title_Arabic', models.CharField(max_length=100, null=True)),
                ('content_Arabic', models.TextField(null=True)),
                ('image', models.ImageField(upload_to='Home Slideshow')),
            ],
            options={
                'verbose_name_plural': 'Home Slideshow',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='post_images')),
            ],
        ),
        migrations.CreateModel(
            name='Services_Cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_English', models.CharField(max_length=100, null=True)),
                ('description_English', models.TextField(null=True)),
                ('content_English', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('title_French', models.CharField(max_length=100, null=True)),
                ('description_French', models.TextField(null=True)),
                ('content_French', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('title_Arabic', models.CharField(max_length=100, null=True)),
                ('description_Arabic', models.TextField(null=True)),
                ('content_Arabic', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='Services')),
                ('cover_image', models.ImageField(null=True, upload_to='Services')),
            ],
            options={
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Services_Slideshow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_English', models.CharField(max_length=100, null=True)),
                ('content_English', models.TextField(null=True)),
                ('title_French', models.CharField(max_length=100, null=True)),
                ('content_French', models.TextField(null=True)),
                ('title_Arabic', models.CharField(max_length=100, null=True)),
                ('content_Arabic', models.TextField(null=True)),
                ('image', models.ImageField(upload_to='Services Slideshow')),
            ],
            options={
                'verbose_name_plural': 'Services Slideshow',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Training_Slideshow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_English', models.CharField(max_length=100, null=True)),
                ('content_English', models.TextField(null=True)),
                ('title_French', models.CharField(max_length=100, null=True)),
                ('content_French', models.TextField(null=True)),
                ('title_Arabic', models.CharField(max_length=100, null=True)),
                ('content_Arabic', models.TextField(null=True)),
                ('image', models.ImageField(upload_to='Training Slideshow')),
            ],
            options={
                'verbose_name_plural': 'Training Slideshow',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Training_Cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_English', models.CharField(max_length=100, null=True)),
                ('description_English', models.TextField(null=True)),
                ('content_English', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('title_French', models.CharField(max_length=100, null=True)),
                ('description_French', models.TextField(null=True)),
                ('content_French', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('title_Arabic', models.CharField(max_length=100, null=True)),
                ('description_Arabic', models.TextField(null=True)),
                ('content_Arabic', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='Training')),
                ('cover_image', models.ImageField(null=True, upload_to='Training')),
                ('tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.tag')),
            ],
            options={
                'verbose_name_plural': 'Training',
            },
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(blank=True, max_length=20, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('phoneNumber', models.IntegerField()),
                ('profileImage', models.ImageField(blank=True, null=True, upload_to='')),
                ('groups', models.ManyToManyField(blank=True, to='API.Group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='prof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.CharField(max_length=40)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receit', models.ImageField(blank=True, null=True, upload_to=API.models.upload_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('prof', models.ManyToManyField(blank=True, to='API.prof')),
            ],
        ),
        migrations.CreateModel(
            name='level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.category')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('video', models.FileField(upload_to='video_lessons')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('groups', models.ManyToManyField(to='API.Group')),
                ('locked', models.ManyToManyField(blank=True, related_name='locked_lessons', to='API.Group')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.unit')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.level'),
        ),
        migrations.AddField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.prof'),
        ),
        migrations.AddField(
            model_name='category',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.module'),
        ),
    ]
