# Generated by Django 3.1.5 on 2021-07-14 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_account_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.CharField(default=111111111, max_length=60),
            preserve_default=False,
        ),
    ]
