# Generated by Django 3.1.5 on 2021-07-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_remove_account_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='phone_number',
            field=models.CharField(default=111111, max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='phoneNumber',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
