# Generated by Django 3.1.5 on 2021-07-14 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_auto_20210714_1310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
    ]
