# Generated by Django 3.1.5 on 2021-07-14 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_auto_20210714_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='phone_number',
        ),
    ]
